<SupplyPointClass>").append(
        "</Initiator><ChangeReasonCode>").append(changeReasonCode.getCode()).append(
        "</ChangeReasonCode><SupplyPointClass>").append(supplyPointClass).append(
        "</SupplyPointClass><RegulatoryAreaCode>").append(regulatoryAreaCode).append(
        "</RegulatoryAreaCode><Role>").append(role).append(
        "</Role><Participant>").append(participant).append(
        "</Participant><RoleStatus>").append(
        roleStatus.name().charAt(0)).append(
        "</RoleStatus><DistributionLossFactorCode>").append(
        distributionLossFactorCode).append(
        "</DistributionLossFactorCode><TransmissionNodeIdentifier>").append(
        transmissionNodeIdentifier).append(
        "</TransmissionNodeIdentifier><SharedIsolationPointFlag>").append(
        sharedIsolationPointFlag).append(
        "</SharedIsolationPointFlag><UniqueServicePointStatus>").append(
        uniqueServicePointStatus).append(
        "</UniqueServicePointStatus><ActualEndDate>").append(
        actualEndDate).append(
        "</ActualEndDate><ScheduledDate>").append(
        scheduledDate).append(
        "</ScheduledDate><TransactionType>CATSChangeRequest</TransactionType><UniqueServiceIdentifier>").append(
        uniqueServiceIdentifier).append(
        "</UniqueServiceIdentifier><TransactionStatus>").append(
        transactionStatus.getCode()).append(
        "</TransactionStatus><Priority>").append(
        priority).append(
        "</Priority><ExternalTransactionID>").append(
        externalTransactionId).append(
        "</ExternalTransactionID>")